---
- name: add client.openstack
  shell: ceph auth add client.openstack mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=volumes, allow rwx pool=vms, allow rwx pool=images, allow rwx pool=backups, allow rwx pool=metrics'

- name: extract ceph client key for client.openstack
  shell: ceph auth get client.openstack |grep key | awk '{print $3}'
  register: os_key

- debug:
    msg: "Found client.openstack key: {{os_key.stdout}}"

- name: grep fsid
  shell: grep fsid /etc/ceph/ceph.conf | awk '{print $3}'
  register: ceph_fsid

- debug:
    msg: "Found ceph fsid: {{ceph_fsid.stdout}}"

- name: Pause to run playbook
  pause: prompt='Did you run the above ansible playbook??? Press return to continue. Press Ctrl+c and then "a" to abort'
