---
monitor_interface: eth0
radosgw_interface: eth0
journal_size: 5120
public_network: 172.18.0.240/24
ceph_docker_image: rhceph/rhceph-4-rhel8
containerized_deployment: true
ceph_docker_registry: classroom.example.com:5000
ceph_origin: repository
ceph_repository: rhcs
ceph_repository_type: cdn
ceph_rhcs_version: 4
dashboard_admin_user: admin
dashboard_admin_password: r3dh4t1!
grafana_admin_user: admin
grafana_admin_password: r3dh4t1!
ceph_conf_overrides:
  global:
    mon_pg_warn_min_per_osd: 0
